function getURLVar(key){var value=[];var query=String(document.location).split('?');if(query[1]){var part=query[1].split('&');for(i=0;i<part.length;i++){var data=part[i].split('=');if(data[0]&&data[1]){value[data[0]]=data[1];}}
if(value[key]){return value[key];}else{return'';}}}
$(document).ready(function(){$('button[type=\'submit\']').on('click',function(){$("form[id*='form-']").submit();});$('.text-danger').each(function(){var element=$(this).parent().parent();if(element.hasClass('form-group')){element.addClass('has-error');}});$('[data-toggle=\'tooltip\']').tooltip({container:'body',html:true});$(document).ajaxStop(function(){$('[data-toggle=\'tooltip\']').tooltip({container:'body'});});$.event.special.remove={remove:function(o){if(o.handler){o.handler.apply(this,arguments);}}}
$('[data-toggle=\'tooltip\']').on('remove',function(){$(this).tooltip('destroy');});$('[data-captcha]').each(function(){var element=this;html='<div id="captcha" data-target="'+ $(this).attr('data-captcha')+'">';html+='  <div id="captcha-message"></div>';html+='  <div id="captcha-image"></div>';html+='  <div><button type="button" id="button-captcha" data-toggle="tooltip" title="Refresh" class="btn btn-link"><i class="fa fa-refresh"></i></button></div>';html+='</div>';$(this).html(html);$($('#captcha').attr('data-captcha')).prop('disabled',true);$('#captcha-image').on('click','a',function(e){e.preventDefault();});$('#button-captcha').on('click',function(){$.ajax({url:'index.php?route=common/captcha',dataType:'json',beforeSend:function(){$('#button-captcha').find('i').addClass('fa-spin');},complete:function(){$('#button-captcha').find('i').removeClass('fa-spin');},success:function(json){$('#captcha .text-danger').remove();if(json['error']){$('#captcha-message').html('<div class="bg-danger">'+ json['error']+'</div>');$('#button-captcha').prop('disabled',true);}
if(json['message']){$('#captcha-message').html('<div class="bg-info">'+ json['message']+'</div>');}
if(json['image']){html='<ul class="list-inline">';for(i=0;i<json['image'].length;i++){html+='<li><a href="'+ json['image'][i]['href']+'"><img src="'+ json['image'][i]['image']+'" alt="" title="" /></a></li>';}
html+='</ul>';$('#captcha-image').html(html);}
$('#captcha-image').one('click','a',function(e){var element=this;$(element).addClass('active');$.ajax({url:$(this).attr('href'),dataType:'json',beforeSend:function(){$('#button-captcha').find('i').addClass('fa-spin');},complete:function(){$('#button-captcha').find('i').removeClass('fa-spin');},success:function(json){$('#captcha .text-danger').remove();if(json['error']){if(json['total']<3){$('#captcha-image').after('<div class="text-danger">'+ json['error']+'</div>');$('#button-captcha').trigger('click');}else{$('#captcha-message').html('<div class="bg-danger">'+ json['error']+'</div>');$('#button-captcha').prop('disabled',true);}}
if(json['success']){$('#captcha-message').html('<div class="bg-success"><i class="fa fa-check-circle"></i> '+ json['success']+'</div>');$($('#captcha').attr('data-target')).prop('disabled',false);$('#button-captcha').prop('disabled',true);}},error:function(xhr,ajaxOptions,thrownError){alert(thrownError+"\r\n"+ xhr.statusText+"\r\n"+ xhr.responseText);}});});},error:function(xhr,ajaxOptions,thrownError){alert(thrownError+"\r\n"+ xhr.statusText+"\r\n"+ xhr.responseText);}});});$('#button-captcha').trigger('click');});$(document).on('click','[data-event="image-browse"]',function(e){e.preventDefault();var node=this;$('#form-upload').remove();$('body').prepend('<form enctype="multipart/form-data" id="form-upload" style="display: none;"><input type="file" name="image" value="" /></form>');$('#form-upload input[name="image"]').trigger('click');if(typeof timer!='undefined'){clearInterval(timer);}
timer=setInterval(function(){if($('#form-upload input[name="image"]').val()!=''){clearInterval(timer);$.ajax({url:'index.php?route=common/image&member_token='+ getURLVar('member_token'),type:'post',data:new FormData($('#form-upload')[0]),dataType:'json',cache:false,contentType:false,processData:false,beforeSend:function(){$(node).button('loading');},complete:function(){$(node).button('reset');},success:function(json){if(json['error']){alert(json['error']);}
if(json['filename']){$($(node).attr('data-target')).attr('value',json['filename']);}
if(json['image']){$($(node).attr('data-image')).attr('src',json['image']);}
if(json['thumb']){$($(node).attr('data-thumb')).attr('src',json['thumb']);}},error:function(xhr,ajaxOptions,thrownError){alert(thrownError+"\r\n"+ xhr.statusText+"\r\n"+ xhr.responseText);}});}},500);});$(document).on('click','[data-event="image-placeholder"]',function(){$($(this).attr('data-target')).attr('value','');$($(this).attr('data-thumb')).attr('src',$(this).attr('data-placeholder'));});$('#float-switch').click(function(){if($('#float-menu').hasClass('open')){$('#float-menu').removeClass('open');$(this).removeClass('open');$('i',this).removeClass('fa-close');$('i',this).addClass('fa-indent');}else{$('#float-menu').addClass('open');$(this).addClass('open');$('i',this).removeClass('fa-indent');$('i',this).addClass('fa-close');}});$('.newsletter').find('button').on('click',function(){var element=this;$.ajax({url:'index.php?route=cms/newsletter&email='+ encodeURIComponent($(this).parent().parent().find('input[name="newsletter"]').val()),beforeSend:function(){$(element).prop('disabled',true);},complete:function(){$(element).prop('disabled',false);},dataType:'html',success:function(data){$('#modal-newsletter').remove();html='<div id="modal-newsletter" class="modal">';html+='  <div class="modal-dialog">';html+='    <div class="modal-content">';html+='      <div class="modal-header">';html+='        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>';html+='        <h4 class="modal-title">Sign up to our newsletter</h4>';html+='      </div>';html+='      <div class="modal-body">'+ data+'</div>';html+='    </div>';html+='  </div>';html+='</div>';$('body').append(html);$('#modal-newsletter').modal('show');},error:function(xhr,ajaxOptions,thrownError){alert(thrownError+"\r\n"+ xhr.statusText+"\r\n"+ xhr.responseText);}});});});